name: Bug Report
description: If something isn't working as expected.
labels:
  - bug
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        Please see [the guide](https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce) too.
        devcontainer.json should be not partial but complete configuration.
        Please remove unneeded configuration to reproduce the issue.
      value: |
        .devcontainer/devcontainer.json

        ```json

        ```

        Other related code

        ```

        ```

        Executed command and output

        ```console
        $ 
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
      description: Additional information about the discussion.
    validations:
      required: false
